project_id = "xjcfyfkpavyonxrdczgs"

[functions.ninjavan-order]
verify_jwt = false

[functions.ninjavan-cancel]
verify_jwt = false

[functions.ninjavan-waybill]
verify_jwt = false

[functions.merge-waybills]
verify_jwt = false

[functions.woocommerce-webhook]
verify_jwt = false

[functions.ninjavan-webhook]
verify_jwt = false
