-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bundles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  units integer NOT NULL DEFAULT 1,
  price_normal numeric NOT NULL DEFAULT 0,
  price_shopee numeric NOT NULL DEFAULT 0,
  price_tiktok numeric NOT NULL DEFAULT 0,
  product_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  price_normal_np numeric NOT NULL DEFAULT 0,
  price_normal_ep numeric NOT NULL DEFAULT 0,
  price_normal_ec numeric NOT NULL DEFAULT 0,
  price_shopee_np numeric NOT NULL DEFAULT 0,
  price_shopee_ep numeric NOT NULL DEFAULT 0,
  price_shopee_ec numeric NOT NULL DEFAULT 0,
  price_tiktok_np numeric NOT NULL DEFAULT 0,
  price_tiktok_ep numeric NOT NULL DEFAULT 0,
  price_tiktok_ec numeric NOT NULL DEFAULT 0,
  CONSTRAINT bundles_pkey PRIMARY KEY (id),
  CONSTRAINT bundles_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.customer_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  no_tempahan text NOT NULL,
  id_sale text,
  marketer_id uuid,
  marketer_id_staff text NOT NULL,
  marketer_name text NOT NULL,
  no_phone text NOT NULL,
  alamat text NOT NULL,
  poskod text NOT NULL,
  bandar text NOT NULL,
  negeri text NOT NULL,
  produk text NOT NULL,
  sku text NOT NULL,
  kuantiti integer NOT NULL DEFAULT 1,
  harga_jualan_produk numeric DEFAULT 0,
  harga_jualan_sebenar numeric NOT NULL,
  harga_jualan_agen numeric DEFAULT 0,
  kos_pos numeric DEFAULT 0,
  kos_produk numeric DEFAULT 0,
  profit numeric DEFAULT 0,
  kurier text,
  berat_parcel integer DEFAULT 0,
  no_tracking text,
  status_parcel text DEFAULT 'Pending'::text,
  nota_staff text,
  tarikh_tempahan text NOT NULL,
  date_order date DEFAULT CURRENT_DATE,
  date_processed date,
  jenis_platform text,
  jenis_customer text,
  cara_bayaran text,
  delivery_status text DEFAULT 'Pending'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  tarikh_bayaran date,
  jenis_bayaran text,
  bank text,
  receipt_image_url text,
  waybill_url text,
  date_return date,
  seo text,
  jenis_closing text,
  marketer_lead_id_staff text,
  admin_id_staff text,
  prospect_id uuid,
  CONSTRAINT customer_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customer_purchases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  seller_id uuid,
  bundle_id uuid,
  product_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  total_price numeric NOT NULL DEFAULT 0,
  payment_method text CHECK (payment_method IS NULL OR (payment_method = ANY (ARRAY['Online Transfer'::text, 'COD'::text, 'Cash'::text]))),
  remarks text DEFAULT 'Customer purchase'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  closing_type text CHECK (closing_type IS NULL OR (closing_type = ANY (ARRAY['Website'::text, 'WhatsappBot'::text, 'Call'::text, 'Manual'::text, 'Live'::text, 'Shop'::text, 'Walk In'::text]))),
  tracking_number text,
  platform text DEFAULT 'Manual'::text,
  ninjavan_order_id text,
  delivery_status text DEFAULT 'Pending'::text,
  date_processed date,
  date_return date,
  tarikh_bayaran date,
  seo text,
  order_from text,
  attachment_url text,
  marketer_id uuid,
  marketer_id_staff text,
  marketer_name text,
  jenis_platform text,
  jenis_customer text,
  jenis_closing text,
  harga_jualan_produk numeric,
  kos_pos numeric DEFAULT 0,
  kos_produk numeric DEFAULT 0,
  profit numeric DEFAULT 0,
  date_order date DEFAULT CURRENT_DATE,
  receipt_image_url text,
  waybill_url text,
  jenis_bayaran text,
  bank text,
  alamat text,
  bandar text,
  poskod text,
  negeri text,
  no_phone text,
  produk text,
  sku text,
  kurier text,
  no_tracking text,
  cara_bayaran text,
  nota_staff text,
  id_sale text,
  woo_order_id integer,
  logistic_bundle_id uuid,
  CONSTRAINT customer_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT customer_purchases_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_purchases_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT customer_purchases_bundle_id_fkey FOREIGN KEY (bundle_id) REFERENCES public.bundles(id),
  CONSTRAINT customer_purchases_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT customer_purchases_marketer_id_fkey FOREIGN KEY (marketer_id) REFERENCES public.profiles(id),
  CONSTRAINT customer_purchases_logistic_bundle_id_fkey FOREIGN KEY (logistic_bundle_id) REFERENCES public.logistic_bundles(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text NOT NULL,
  address text,
  state text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  postcode text,
  city text,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.device_setting (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  device_id text,
  instance text,
  webhook_id text,
  provider text DEFAULT 'whacenter'::text,
  api_key text,
  id_device text,
  phone_number text,
  status_wa text DEFAULT 'disconnected'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT device_setting_pkey PRIMARY KEY (id),
  CONSTRAINT device_setting_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.logistic_bundle_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bundle_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT logistic_bundle_items_pkey PRIMARY KEY (id),
  CONSTRAINT logistic_bundle_items_bundle_id_fkey FOREIGN KEY (bundle_id) REFERENCES public.logistic_bundles(id),
  CONSTRAINT logistic_bundle_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.logistic_bundles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  logistic_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  sku text,
  total_price numeric NOT NULL DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  price_np numeric NOT NULL DEFAULT 0,
  price_ep numeric NOT NULL DEFAULT 0,
  price_ec numeric NOT NULL DEFAULT 0,
  CONSTRAINT logistic_bundles_pkey PRIMARY KEY (id),
  CONSTRAINT logistic_bundles_logistic_id_fkey FOREIGN KEY (logistic_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.logistic_stock_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  logistic_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  description text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  processed_by uuid,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT logistic_stock_requests_pkey PRIMARY KEY (id),
  CONSTRAINT logistic_stock_requests_logistic_id_fkey FOREIGN KEY (logistic_id) REFERENCES public.profiles(id),
  CONSTRAINT logistic_stock_requests_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT logistic_stock_requests_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.ninjavan_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id text NOT NULL,
  client_secret text NOT NULL,
  sender_name text NOT NULL,
  sender_phone text NOT NULL,
  sender_email text NOT NULL,
  sender_address1 text NOT NULL,
  sender_address2 text,
  sender_postcode text NOT NULL,
  sender_city text NOT NULL,
  sender_state text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ninjavan_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ninjavan_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  access_token text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ninjavan_tokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pnl_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role text NOT NULL DEFAULT 'marketer'::text CHECK (role = ANY (ARRAY['marketer'::text, 'admin'::text])),
  min_sales numeric NOT NULL DEFAULT 0,
  max_sales numeric,
  roas_min numeric NOT NULL DEFAULT 0,
  roas_max numeric NOT NULL DEFAULT 99,
  commission_percent numeric NOT NULL DEFAULT 0,
  bonus_amount numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pnl_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sku text NOT NULL,
  base_cost numeric NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 0,
  stock_in integer NOT NULL DEFAULT 0,
  stock_out integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text NOT NULL,
  full_name text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  password_hash text NOT NULL DEFAULT ''::text,
  idstaff text UNIQUE,
  is_active boolean DEFAULT true,
  whatsapp_number text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prospects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nama_prospek text NOT NULL,
  no_telefon text NOT NULL,
  niche text NOT NULL,
  jenis_prospek text NOT NULL,
  tarikh_phone_number date,
  admin_id_staff text,
  created_by uuid,
  status_closed text,
  price_closed numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  marketer_id_staff text,
  count_order integer NOT NULL DEFAULT 0,
  profile text,
  admin_claimed_at timestamp with time zone,
  CONSTRAINT prospects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.spends (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product text NOT NULL,
  jenis_platform text NOT NULL,
  total_spend numeric NOT NULL DEFAULT 0,
  tarikh_spend date NOT NULL DEFAULT CURRENT_DATE,
  marketer_id_staff text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  jenis_closing text,
  CONSTRAINT spends_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stock_in_logistic (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  logistic_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  description text,
  date timestamp with time zone NOT NULL DEFAULT now(),
  source_type text NOT NULL DEFAULT 'hq'::text CHECK (source_type = ANY (ARRAY['hq'::text, 'transfer'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT stock_in_logistic_pkey PRIMARY KEY (id),
  CONSTRAINT stock_in_logistic_logistic_id_fkey FOREIGN KEY (logistic_id) REFERENCES public.profiles(id),
  CONSTRAINT stock_in_logistic_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.stock_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  type text NOT NULL,
  quantity integer NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  description text,
  master_agent_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT stock_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.stock_out_logistic (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  logistic_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  description text,
  date timestamp with time zone NOT NULL DEFAULT now(),
  recipient_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT stock_out_logistic_pkey PRIMARY KEY (id),
  CONSTRAINT stock_out_logistic_logistic_id_fkey FOREIGN KEY (logistic_id) REFERENCES public.profiles(id),
  CONSTRAINT stock_out_logistic_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT stock_out_logistic_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.webhook_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  webhook_type text NOT NULL,
  request_method text,
  request_body jsonb,
  request_headers jsonb,
  device_id text,
  sender text,
  message text,
  parsed_data jsonb,
  response_status integer,
  response_body jsonb,
  error_message text,
  processing_time_ms integer,
  ip_address text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webhook_logs_pkey PRIMARY KEY (id)
);